### ISSUE TITLE
what function createColoring mwan

### ISSUE THREAD

**Issue by lihongyi1234** [DanielZint/dmo_templated#10]
![image](https://github.com/user-attachments/assets/1c8d5e70-71bc-46e0-8bfa-40324d78fd62)
what's function createColoring, it looks so puzzled

**Comment by daniel-zint** [comment]
The function performs a greedy vertex coloring ([Wikipedia - Graph Coloring](https://en.wikipedia.org/wiki/Graph_coloring)). All vertices of the same color can be optimized in parallel without causing any race conditions.

**Comment by lihongyi1234** [comment]
> The function performs a greedy vertex coloring ([Wikipedia - Graph Coloring](https://en.wikipedia.org/wiki/Graph_coloring)). All vertices of the same color can be optimized in parallel without causing any race conditions.

get it, thanks
